### ISSUE TITLE
Unsafe API endpoints

### ISSUE THREAD

**Issue by bastihav** [upb-uc4/University-Credits-4.0#122]
/users/{username}/role
/users/admins/{username}
/users/students/{username}
/users/lecturers/{username}

this can lead to problems, as a user named "admins", "students" or "lecturers", paired with a user named "role", can lead to ambiguous routes.

**Comment by janniclas** [comment]
I would recommend switching to ids. thats the usual api behaviour when dealing with subelements of a larger collection (a user from users collection)
Google provides some useful api design tips and standard stuff here :) 
https://cloud.google.com/apis/design/design_patterns
