### ISSUE TITLE
Possible Password Leak

### ISSUE THREAD

**Issue by david-buderus** [upb-uc4/University-Credits-4.0#135]
## Problem
In the current implementation a big password leak could happen if an intruder is able to connect to Kafka.  
If he would subscribe to the AuthenticationTopic, he would get all users and corresponding passwords in plain text of the running session.

## Solution Attempt
- Create an intern endpoint in the AuthenticationService to add the user with his password (which only admin-accounts can use)
- Remove the AuthenticationTopic 
- If an user gets added, the UserService makes a direkt call to the AuthenticationService

### Problems with this attempt
- It would be overhead to have the change password in the UserService, it should be in the AuthenticationService
- The AuthenticationService gets more vulnerable (Possible solution: Traefik only forwards the exakt path to the change password endpoint)

## Side Notes
- The DeletionTopic is not affected, because it does not send any critical information

**Comment by lrschaef** [comment]
Topics are indeed a risky "topic". We should never ever send passwords or authentication data via a topic, even though Kafka is not accessible from the outside.

**Comment by ldklenner** [comment]
A brief search reveals that there exists efforts to extend/augment Kafka with several [security aspects](https://medium.com/@stephane.maarek/introduction-to-apache-kafka-security-c8951d410adf) like integrity, authentification and auzthorization. However, I don't think that these described methods are infeasible to implement as most aspects are left up for implementation. Which means that, for example we have to implement a authentication on top of Kakfa.

Therefore, I think your proposed solution is the way to go.
